table Fact_電力密集度年
	lineageTag: fa060000-fa06-4000-8006-fa0600000006

	column 西元年
		dataType: int64
		lineageTag: fa060001-fa06-4001-8006-fa0600000006
		summarizeBy: sum
		sourceColumn: 西元年

		annotation SummarizationSetBy = Automatic

	column 行業別
		dataType: string
		lineageTag: fa060002-fa06-4002-8006-fa0600000006
		summarizeBy: none
		sourceColumn: 行業別

		annotation SummarizationSetBy = Automatic

	column GDP代碼
		dataType: string
		lineageTag: fa060003-fa06-4003-8006-fa0600000006
		summarizeBy: none
		sourceColumn: GDP代碼

		annotation SummarizationSetBy = Automatic

	column 電力消費_千度
		dataType: double
		lineageTag: fa060004-fa06-4004-8006-fa0600000006
		summarizeBy: sum
		sourceColumn: 電力消費_千度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GDP合計_連鎖實質_百萬元
		dataType: double
		lineageTag: fa060005-fa06-4005-8006-fa0600000006
		summarizeBy: sum
		sourceColumn: GDP合計_連鎖實質_百萬元

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 電力密集度_千度per百萬元
		dataType: double
		lineageTag: fa060006-fa06-4006-8006-fa0600000006
		summarizeBy: sum
		sourceColumn: 電力密集度_千度per百萬元

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa060007-fa06-4007-8006-fa0600000006
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_電力密集度年 = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\職訓課\Electricity_dataset\data\electricity_intensity_annual.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    TypeChanged = Table.TransformColumnTypes(Promoted, {
				        {"西元年", Int64.Type},
				        {"行業別", type text}, {"GDP代碼", type text},
				        {"電力消費_千度", type number},
				        {"GDP合計_連鎖實質_百萬元", type number},
				        {"電力密集度_千度per百萬元", type number}
				    }),
				    DateAdded = Table.AddColumn(TypeChanged, "Date",
				        each #date([西元年], 1, 1), type date)
				in
				    DateAdded

	annotation PBI_ResultType = Table

	annotation PBI_Id = fa060000fa0640008006fa0600000006

	annotation PBI_NavigationStepName = Navigation

