table Fact_TechHubPower
	lineageTag: fa0a0000-fa0a-4000-800a-fa0a0000000a

	column YearMonth
		dataType: int64
		lineageTag: fa0a0001-fa0a-4001-800a-fa0a0000000a
		summarizeBy: sum
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: fa0a0002-fa0a-4002-800a-fa0a0000000a
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column PowerUsage_100M_kWh
		dataType: double
		lineageTag: fa0a0003-fa0a-4003-800a-fa0a0000000a
		summarizeBy: sum
		sourceColumn: PowerUsage_100M_kWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StationName
		dataType: string
		lineageTag: fa0a0004-fa0a-4004-800a-fa0a0000000a
		summarizeBy: none
		sourceColumn: StationName

		annotation SummarizationSetBy = Automatic

	column MeanTemp
		dataType: double
		lineageTag: fa0a0005-fa0a-4005-800a-fa0a0000000a
		summarizeBy: sum
		sourceColumn: MeanTemp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SunshineHrs
		dataType: double
		lineageTag: fa0a0006-fa0a-4006-800a-fa0a0000000a
		summarizeBy: sum
		sourceColumn: SunshineHrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa0a0007-fa0a-4007-800a-fa0a0000000a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 科學園區
		dataType: string
		lineageTag: fa0a0008-fa0a-4008-800a-fa0a0000000a
		summarizeBy: none
		sourceColumn: 科學園區

		annotation SummarizationSetBy = Automatic

	partition Fact_TechHubPower = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\職訓課\Electricity_dataset\data\前一千筆_vw_TechClimate_Base.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    TypeChanged = Table.TransformColumnTypes(Promoted, {
				        {"YearMonth", Int64.Type},
				        {"District", type text},
				        {"PowerUsage_100M_kWh", type number},
				        {"StationName", type text},
				        {"MeanTemp", type number},
				        {"SunshineHrs", type number}
				    }),
				    YearAdded = Table.AddColumn(TypeChanged, "Year",
				        each Number.IntegerDivide([YearMonth], 100), Int64.Type),
				    MonthAdded = Table.AddColumn(YearAdded, "Month",
				        each Number.Mod([YearMonth], 100), Int64.Type),
				    DateAdded = Table.AddColumn(MonthAdded, "Date",
				        each #date([Year], [Month], 1), type date),
				    ParkAdded = Table.AddColumn(DateAdded, "科學園區",
				        each if List.Contains({"安定", "新市"}, [District]) then "南部科學園區"
				        else if List.Contains({"寶山", "新竹市"}, [District]) then "新竹科學園區"
				        else "中部科學園區",
				        type text),
				    Selected = Table.SelectColumns(ParkAdded,
				        {"YearMonth", "District", "科學園區", "PowerUsage_100M_kWh",
				         "StationName", "MeanTemp", "SunshineHrs", "Date"})
				in
				    Selected

	annotation PBI_ResultType = Table

	annotation PBI_Id = fa0a0000fa0a4000800afa0a0000000a

	annotation PBI_NavigationStepName = Navigation

